### PR TITLE
Add attribute to allow setting of rsyslog.d configuration directory mode for security compliance

### PR DESCRIPTION
**Pull request by bdd4329**
### Description

I am required by my security compliance rules to set the rsyslog.d directory to 750 or 700 (not 755). This PR leaves the default as 755, but allows an attribute to be set to change this mode. This may be an Obvious Fix.

### Issues Resolved

Fixes not being able to set the rsyslog.d directory mode.

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by bdd4329** [comment]
Is there anything else that I need to do to get this change reviewed? It has been sitting here for some time.

**Comment by Xorima** [comment]
Hey @bdd4329 

Sous-Chefs have recently inherited this cookbook, can you pop in a changelog entry so we can get this shipped please?

Thanks!

**Comment by bdd4329** [comment]
@Xorima Done.

**Review by Xorima — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [7.2.0](https://github.com/sous-chefs/rsyslog/releases/tag/7.2.0)

**Comment by Xorima** [comment]
@bdd4329 this was actually released as 7.2.1 due to a bug in the auto release system (it's still new :joy: )

**Pull request merged**
