### PR TITLE
Support for Rainer Script; Fix Travis CI

### PR DESCRIPTION
**Pull request by voroniys**
### Description

Fix Travis CI build
### Issues Resolved

Failing Travis CI
### Check List

- [+ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ +] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by voroniys** [comment]
Obvious Fix

**Comment by voroniys** [comment]
Build failed due to timeout on Travis CI

**Comment by tas50** [comment]
@voroniys If you could rebase this I'll gladly merge it in.

**Comment by voroniys** [comment]
This is the maximum I can do. It is more than a year and half passed.

**Comment by Xorima** [comment]
Closing due to inactivity. 

If this is still wanted please reopen or open another pull request. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs

**Pull request closed without merging**
