### PR TITLE
#146 Exclude Amazon Linux from old versions check

### PR DESCRIPTION
**Pull request by blueben**
### Description
 
Obvious fix. Excludes Amazon Linux from old-versions check.

### Issues Resolved

GH-146

### CODE REVIEW

**Comment by tas50** [comment]
This is going to cause failures on Amazon 1.x (2013-2018 releases) where they match up with RHEL 6 not RHEL 7

**Comment by blueben** [comment]
@tas50 What does Amazon Linux 1.x report for 'ohai platform platform_family platform_version' ?

**Comment by tas50** [comment]
2013.03 -  2018.03 at the moment. I'm not sure if they'll continue to release new versions so at some point there *might* be a 2019.03

**Comment by blueben** [comment]
@tas50 I'm not sure what failure this will cause. Right now, the logic will only apply the rsyslog3/4 config if the OS is not Amazon Linux, is RHEL, and is less than 6.

**Comment by tas50** [comment]
Amazon 201X is RHEL 6 though so you probably do want to catch those, but not Amazon Linux 2.X which is RHEL 7.

**Comment by blueben** [comment]
Does RHEL 6 come with rsyslog 3 or 4? I may have another workaround; I'll update the PR later.

**Comment by blueben** [comment]
Hey @tas50. Looking at RHEL6, it appears to be using syslog 5. This should mean that this test is safe as Amazon Linux 1 won't need to be captured by the conditional.

**Comment by Xorima** [comment]
Closing due to inactivity. 

If this is still wanted please reopen or open another pull request. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs

**Pull request closed without merging**
