### PR TITLE
Enabled custom  35-server-per-host.conf templates

### LINKED ISSUE #173: NGINX logs are logged twice
Using this cookbook (`v7.0.1`) with Chef (`16.5.77`), I get the undesired behavior of NGINX logs getting logged twice in `syslog` and `messages` because the way the [35-server-per-host.conf.erb](https://github.com/chef-cookbooks/rsyslog/blob/master/templates/default/35-server-per-host.conf.erb) template is written.

According to [NGINX docs](http://nginx.org/en/docs/syslog.html), by default the `severity` is set as `info`, and in the [35-server-per-host.conf.erb](https://github.com/chef-cookbooks/rsyslog/blob/master/templates/default/35-server-per-host.conf.erb) template we can find that:

```
$template PerHostSyslog,"<%= node['rsyslog']['log_dir'] %>/<%= node['rsyslog']['per_host_dir'] %>/syslog"
...
$template PerHostMessages,"<%= node['rsyslog']['log_dir'] %>/<%= node['rsyslog']['per_host_dir'] %>/messages"
...
*.*;auth,authpriv.none  -?PerHostSyslog
...
*.=info;*.=notice;*.=warn;\
  auth,authpriv.none;\
  cron,daemon.none;\
  mail,news.none        -?PerHostMessages
```

so **it matches both PerHostSyslog and PerHostMessages templates**.

I've found a workaround in NGINX, which is set the `severity` to `crit` so it gets only logged in `syslog`, but I don't really know if this is OK (my experience with `rsyslog` and `syslog` is very limited).

Would it be possible that the [server.rb](https://github.com/chef-cookbooks/rsyslog/blob/master/recipes/server.rb#L32) recipe had the `source` property set via attribute? E.g:

```diff
diff --git a/recipes/server.rb b/recipes/server.rb
index 7ea0e53..0eeb0bc 100644
--- a/recipes/server.rb
+++ b/recipes/server.rb
@@ -30,7 +30,7 @@ directory node['rsyslog']['log_dir'] do
 end
 
 template "#{node['rsyslog']['config_prefix']}/rsyslog.d/35-server-per-host.conf" do
-  source   '35-server-per-host.conf.erb'
+  source   node['rsyslog']['server-per-host-template']
   owner    node['rsyslog']['config_files']['owner']
   group    node['rsyslog']['config_files']['group']
   mode     node['rsyslog']['config_files']['mode']
```

### PR DESCRIPTION
**Pull request by axl89**
# Description

This enables a complete or partial override of the `35-server-per-host.conf` file.

For instance, disable debug and/or messages, etc.

## Issues Resolved

#173 

## Check List

- [x] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by axl89** [comment]
My plan is to create a wrapper cookbook and set a different template, with the following differences from the original:

```diff
diff --git a/templates/default/35-server-per-host.conf.erb b/templates/default/35-server-per-host.conf.erb
index 91cbcc5..3def571 100644
--- a/templates/default/35-server-per-host.conf.erb
+++ b/templates/default/35-server-per-host.conf.erb
@@ -43,14 +43,6 @@ news.crit               ?PerHostNewsCrit
 news.err                ?PerHostNewsErr
 news.notice             -?PerHostNewsNotice
 
-*.=debug;\
-  auth,authpriv.none;\
-  news.none;mail.none   -?PerHostDebug
-
-*.=info;*.=notice;*.=warn;\
-  auth,authpriv.none;\
-  cron,daemon.none;\
-  mail,news.none        -?PerHostMessages
 
 
 <% unless node['rsyslog']['allow_non_local'] -%>
```

**Comment by axl89** [comment]
Tests are failing, but they are also failing on [master](https://github.com/sous-chefs/rsyslog/runs/1088202789).

**Comment by ramereth** [comment]
@axl89 this cookbook was just transferred to us and we're still in the process of getting it properly imported into Sous Chefs. Please give us a week or so to get ready and we'll have you rebase.

**Review by ramereth — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [7.3.0](https://github.com/sous-chefs/rsyslog/releases/tag/7.3.0)

**Pull request merged**
