### PR TITLE
Bug 119 too many imfiles

### LINKED ISSUE #119: file_input template includes imfile, so cannot by reused
### Cookbook version
4.0.1
### Chef-client version
12.15.19

### Platform Details
Ubuntu 16.04 on AWS

### Scenario:
Can't call the `file_input` resource multiple times with the default template. The config test added in 4.0.1 will fail b/c imfile is included multiple times.

### Steps to Reproduce:
Create multiple `ryslog_file_input` resources using the default template.

### Expected Result:
Successful converge.

### Actual Result:
```
[2016-11-02T21:03:43+00:00] ERROR: Exception handlers complete
ERROR: execute[validate_config] (rsyslog::default line 42) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of rsyslogd -N 1 -f /etc/rsyslog.conf ----
STDOUT:
rsyslogd: version 8.16.0, config validation run (level 1), master config /etc/rsyslog.conf
rsyslogd: module 'imfile' already in this config, cannot be added  [v8.16.0 try http://www.rsyslog.com/e/2221 ]
rsyslogd: module 'imfile' already in this config, cannot be added  [v8.16.0 try http://www.rsyslog.com/e/2221 ]
---- End output of rsyslogd -N 1 -f /etc/rsyslog.conf ----
Ran rsyslogd -N 1 -f /etc/rsyslog.conf returned 1
[2016-11-02T21:03:43+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

The input_file template included in the cookbook should not include imfile or should have some conditional logic to ensure it's only included in one of them. It might make sense to have a dedicated file in `/etc/rsyslog.d` to include `imfile` that is created anytime the `ryslog_file_input` resource is used.

### PR DESCRIPTION
**Pull request by runswithd6s**
In order use the `rsyslog_file_input` resource, `$ModLoad imfile` needs to be
defined only once. Removed it from the `file-input.conf.erb` template file and
added `README.md` instructions to add the `imfile` module to the node to enable.
Added tests for a second log file and for existence of one module load
statement.

### Description

The file_input resource was incorrectly including the legacy `$ModLoad imfile`
declaration in each new config file created from template. Additionally, the
legacy style script prevented newer rsyslog daemons from using `inotify` method.
This commit adds:

  - Legacy configuration file support
  - Ranier style configuration file support
  - Ability to specify imfile module parameters
  - Ability to specify additional resource parameters for `rsyslog_file_input`

### Issues Resolved

Fixed #119.

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by runswithd6s** [comment]
Re-based version.

**Comment by runswithd6s** [comment]
Tests for CentOS 6 are failing due to unrelated changes around imjournal.

**Comment by Xorima** [comment]
Hey @runswithd6s 

Any chance you can rebase this? 

Thanks!

**Comment by ramereth** [comment]
@Xorima any particular reason why this needs a major bump?

**Comment by Xorima** [comment]
> @Xorima any particular reason why this needs a major bump?

The imfile change could catch someone off guard, it's not a big change but let's not surprise people

**Review by ramereth — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [8.0.0](https://github.com/sous-chefs/rsyslog/releases/tag/8.0.0)

**Pull request merged**
